version: '3'
services:
  web:
    build: .
    ports:
      - "5005:8080"
    environment:
      - "TZ=Asia/Ho_Chi_Minh"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
